### ISSUE TITLE
Dynamic config of compression

### ISSUE THREAD

**Issue by mnzsss** [altair823/image_compressor#7]
Hi, I'm new in te rust and I tried use this package for compress images folders, so I tried pass the config `quality` and `size` from the function arguments. You can help me to do that? It's possible pass or nowadays I need pass the fixed config?

```rs
pub fn compress_image<'a>(input_dir: &'a str, compression: f32, resize_percentage: f32) -> &'a str {
	// ...

    let mut comp = FolderCompressor::new(origin, dest);

	// I can pass the function arguments in Factor? like: Factor::new(compression, resize_percentage)

    comp.set_cal_func(|_, _, _| return Factor::new(75., 1.0));

	// ...
}
```

**Comment by altair823** [comment]
It's been a while since I made this library, and the skills to create it were very poor at the time. Now I don't think the set_cal_func function makes sense, but just input factor(config) into the compressor makes a lot more sense. 
So in version 1.3.0, there is a new function `set_factor` added. you can use this function for your purpose. 

Unfortunately, the code cannot be fully tested at this time. So, if you have any problems using it, please point it out. 

And Merry Christmas!

**Comment by mnzsss** [comment]
Oh thanks for help me, I tried use that in `1.2.2` version, when I uprgade to `1.3.0` and use the `set_factor` pass arguments works!

![image](https://user-images.githubusercontent.com/51327920/209443993-635f6af1-2582-4bb4-a89d-f6d290d83dfb.png)

Thank you again and Merry Christmas!
